mod new_solver;
mod old_solver;
mod runtime;

use crate::config::BuildOptions;
use crate::model::{EnumDef, Solver};

trait SolverEmitter {
    fn emit_enum(&self, output: &mut String, enum_def: &EnumDef, options: &BuildOptions);
}

pub fn generate(options: &BuildOptions) -> String {
    let mut output = String::new();
    output.push_str("-- This file was generated by cenum. Do not edit manually.\n\n");
    runtime::emit_runtime(&mut output, options);

    let emitter: Box<dyn SolverEmitter> = match options.solver {
        Solver::Old => Box::new(old_solver::OldSolverEmitter),
        Solver::New => Box::new(new_solver::NewSolverEmitter),
    };

    output.push_str("-- Enums\n");
    for enum_def in &options.enums {
        emitter.emit_enum(&mut output, enum_def, options);
        output.push('\n');
    }

    output.push_str("return table.freeze({\n");
    line(&mut output, 1, "serialize = __CEnumSerialize,");
    line(&mut output, 1, "deserialize = __CEnumDeserialize,");
    for enum_def in &options.enums {
        line(&mut output, 1, &format!("{} = {},", enum_def.name, enum_def.name));
    }
    output.push_str("})\n");

    output
}

fn line(output: &mut String, indent: usize, text: &str) {
    for _ in 0..indent {
        output.push('\t');
    }
    output.push_str(text);
    output.push('\n');
}

fn string_literal(value: &str) -> String {
    let mut result = String::with_capacity(value.len() + 2);
    result.push('"');
    for character in value.chars() {
        match character {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            _ => result.push(character),
        }
    }
    result.push('"');
    result
}

fn enum_set_alias(enum_def: &EnumDef) -> String {
    format!("__CEnum{}Set", enum_def.name)
}

fn enum_item_name_alias(enum_def: &EnumDef) -> String {
    format!("__CEnum{}ItemName", enum_def.name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::BuildOptions;
    use crate::model::{EnumDef, Solver};
    use std::path::PathBuf;

    fn options(solver: Solver) -> BuildOptions {
        BuildOptions {
            output: PathBuf::from("Enums.luau"),
            solver,
            enums: vec![
                EnumDef {
                    name: "TransactionType".to_owned(),
                    items: vec!["Robux".to_owned(), "Tickets".to_owned()],
                },
                EnumDef {
                    name: "TransactionStatus".to_owned(),
                    items: vec!["Pending".to_owned(), "Completed".to_owned(), "Failed".to_owned()],
                },
            ],
        }
    }

    #[test]
    fn old_solver_exports_types_and_returns_table() {
        let output = generate(&options(Solver::Old));

        assert!(output.contains("type __CEnumEnumItem = {"));
        assert!(!output.starts_with("--!strict\n"));
        assert!(output.contains("type __CEnumEnumSet = {"));
        assert!(output.contains("type __CEnumSerializedEnumItem = {"));
        assert!(output.contains("type __CEnumSerializedPrimitive = nil | boolean | number | string"));
        assert!(output.contains("type __CEnumSerializedValue = __CEnumSerializedPrimitive"));
        assert!(output.contains("__syncType: \"CustomEnum\","));
        assert!(output.contains("type __CEnumSerializedMap = {"));
        assert!(output.contains("type __CEnumEnumItemData = {"));
        assert!(output.contains("__CEnumEnumItemMap.__tostring = function(self: __CEnumEnumItemData): string"));
        assert!(output.contains("function __CEnumEnumItemMap.IsA(self: __CEnumEnumItemData, category: string): boolean"));
        assert!(output.contains("const __CEnumEnumSetMethods = {}"));
        assert!(output.contains("const __CEnumCustomEnumSyncType = \"CustomEnum\""));
        assert!(output.contains("const __CEnumMapSyncType = \"Map\""));
        assert!(output.contains(
            "const function __CEnumSerialize(_: any, value: any): __CEnumSerializedValue"
        ));
        assert!(output
            .contains("const function __CEnumDeserialize(enums: { [string]: any }, value: unknown): unknown"));
        assert!(output.contains("error(\"cannot serialize cyclic table\", 2)"));
        assert!(output.contains("serializedTable.__syncType == __CEnumCustomEnumSyncType"));
        assert!(output.contains("local result: { [string]: __CEnumEnumItem } = {}"));
        assert!(!output.contains("export type EnumSet<EnumType, Item = string>"));
        assert!(!output.contains("export type EnumItem<EnumType, Item = string>"));
        assert!(!output.contains("_items"));
        assert!(output.contains("local enumItem = self[name]"));
        assert!(output.contains("type __CEnumTransactionTypeItemName = \"Robux\" | \"Tickets\""));
        assert!(!output.contains("type __CEnumTransactionTypeItem = {"));
        assert!(output.contains("type __CEnumTransactionTypeRobuxItem = {"));
        assert!(output.contains("type __CEnumTransactionTypeTicketsItem = {"));
        assert!(output.contains("export type TransactionType =\n\t__CEnumTransactionTypeRobuxItem"));
        assert!(output.contains("export type TransactionStatus =\n\t__CEnumTransactionStatusPendingItem"));
        assert!(output.contains("Name: \"Robux\","));
        assert!(output.contains("Name: \"Tickets\","));
        assert!(!output.contains("Name: Item,"));
        assert!(output.contains("EnumType: TransactionType,"));
        assert!(output.contains("EnumType: TransactionStatus,"));
        assert!(!output.contains("_enumTypeName: \"TransactionType\""));
        assert!(!output.contains("__CEnumTransactionTypeBrand"));
        assert!(!output.contains("__CEnumTransactionStatusBrand"));
        assert!(!output.contains("export type TransactionType = __CEnumTransactionTypeItem"));
        assert!(!output.contains("export type TransactionType = __CEnumTransactionTypeItem<"));
        assert!(output.contains("type __CEnumTransactionTypeSet = {"));
        assert!(output.contains("local TransactionType: __CEnumTransactionTypeSet"));
        assert!(output.contains("local TransactionType: __CEnumTransactionTypeSet = __CEnumNew("));
        assert!(output.contains("\t\"TransactionType\","));
        assert!(output.contains("\t\t\"Tickets\","));
        assert!(!output.contains("Tickets = table.freeze(setmetatable({"));
        assert!(output.contains("Tickets: __CEnumTransactionTypeTicketsItem,"));
        assert!(!output.contains(")) :: __CEnumTransactionTypeItem"));
        assert!(!output.contains("(TransactionType.Tickets :: any).EnumType = TransactionType"));
        assert!(!output.contains("setmetatable(TransactionType, __CEnumEnumSetMetatable)"));
        assert!(!output.contains("table.freeze(TransactionType)"));
        assert!(!output.contains("setmetatable(TransactionType :: any"));
        assert!(!output.contains("__CEnumTransactionTypeType"));
        assert!(!output.contains("typeof(__CEnumTransactionTypeType)"));
        assert!(!output.contains("__CEnumTransactionTypeItems"));
        assert!(output.contains("\tserialize = __CEnumSerialize,"));
        assert!(output.contains("\tdeserialize = __CEnumDeserialize,"));
        assert!(output.contains("TransactionStatus = TransactionStatus,"));
        assert!(!output.contains("local __CEnumEnumMap ="));
    }

    #[test]
    fn new_solver_uses_item_name_alias() {
        let output = generate(&options(Solver::New));

        assert!(output.contains("type __CEnumTransactionTypeItemName = \"Robux\" | \"Tickets\""));
        assert!(output.contains(
            "export type TransactionType =\n\t__CEnumTransactionTypeRobuxItem"
        ));
        assert!(output.contains("Robux: __CEnumTransactionTypeRobuxItem,"));
    }

    #[test]
    fn runtime_helpers_use_const_declarations() {
        let output = generate(&options(Solver::Old));

        assert!(output.contains("const __CEnumEnumItemMap = {}"));
        assert!(output.contains("const function __CEnumNew"));
    }
}
